# ============================================
# Stage 1: Build Frontend Assets
# ============================================
FROM node:18-alpine AS asset-builder

WORKDIR /build

# Copy package files, lockfile, and build script
COPY package.json package-lock.json ./
COPY copy-assets.js .

# Install exact dependencies from lockfile
RUN npm ci --production

# Create vendor directory structure
RUN mkdir -p src/static/vendor

# Execute asset copy script
RUN npm run build-assets

# ============================================
# Stage 2: Python Application
# ============================================
FROM python:3.13-slim

# Install system dependencies for WeasyPrint (PDF generation)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgobject-2.0-0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libcairo2 \
    libgdk-pixbuf-xlib-2.0-0\
    libffi-dev \
    shared-mime-info \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application's code into the container at /app
COPY . .

# Overwrite vendor static files with those generated by Node
COPY --from=asset-builder /build/src/static/vendor /app/src/static/vendor

# Make the entrypoint script executable
RUN chmod +x ./entrypoint.sh

# Set the entrypoint for the container
ENTRYPOINT ["./entrypoint.sh"]

# ============================================
# Stage 3: Development (adds faker, pytest)
# ============================================
FROM python:3.13-slim AS dev

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgobject-2.0-0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libcairo2 \
    libgdk-pixbuf-xlib-2.0-0\
    libffi-dev \
    shared-mime-info \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-dev.txt requirements.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .
COPY --from=asset-builder /build/src/static/vendor /app/src/static/vendor

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
