[pytest]
# Le dice a pytest que busque los módulos de python aquí
pythonpath = . src
filterwarnings =
    default
    ignore:Identity map already had an identity:sqlalchemy.exc.SAWarning
    ignore::ResourceWarning