{{- if and .Values.persistence.logs.enabled (not .Values.persistence.logs.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opsdeck.fullname" . }}-logs-pvc
  labels:
    {{- include "opsdeck.labels" . | nindent 4 }}
    app.kubernetes.io/component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  {{- if .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  {{- end }}
{{- end }}
