"""Initial migration

Revision ID: 7cd37de826eb
Revises: 
Create Date: 2026-01-20 15:41:47.721989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd37de826eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('secure_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('linkable_id', sa.Integer(), nullable=False),
    sa.Column('linkable_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secure_filename')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index('idx_attachment_linkable', ['linkable_id', 'linkable_type'], unique=False)

    op.create_table('bcdr_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_center', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_center_code'), ['code'], unique=True)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('completion_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'name', name='uq_entity_field_name')
    )
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.create_index('idx_exchange_rate_currency_date', ['currency_code', 'fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rate_currency_code'), ['currency_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rate_fetched_at'), ['fetched_at'], unique=False)

    op.create_table('finance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_provider', sa.String(length=50), nullable=True),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('framework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('framework', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_is_active'), ['is_active'], unique=False)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hiring_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_hired_stage', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('tax_id_override', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('reception_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_recipient', sa.String(length=120), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.Column('notify_days_before', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('email_domains', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('process_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('total_residual_risk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('compliance_status', sa.String(length=50), nullable=True),
    sa.Column('gdpr_dpa_signed', sa.Date(), nullable=True),
    sa.Column('security_assessment_completed', sa.Date(), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('data_storage_region', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threat_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('personal_email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('hide_from_org_chart', sa.Boolean(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('buddy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buddy_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_token'), ['api_token'], unique=True)

    op.create_table('activity_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['security_activity.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_participants',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['security_activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'user_id')
    )
    op.create_table('activity_related_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('related_object_id', sa.Integer(), nullable=False),
    sa.Column('related_object_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['security_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_related_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_related_object_related_object_id'), ['related_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_related_object_related_object_type'), ['related_object_type'], unique=False)

    op.create_table('activity_tags',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['security_activity.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'tag_id')
    )
    op.create_table('asset_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('conducted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conducted_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bcdr_test_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['bcdr_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('legacy_cost_center', sa.String(length=100), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('sla_response_hours', sa.Integer(), nullable=True),
    sa.Column('sla_resolution_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_center.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('send_to_all', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('expected_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('resume_link', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['hiring_stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('threat_type_id', sa.Integer(), nullable=True),
    sa.Column('suggested_impact', sa.Integer(), nullable=True),
    sa.Column('suggested_likelihood', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['risk_catalog.id'], ),
    sa.ForeignKeyConstraint(['threat_type_id'], ['threat_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('version_notes', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('issuer', sa.String(length=100), nullable=True),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('public_body', sa.Text(), nullable=True),
    sa.Column('private_key_location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_frequency', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('is_auto_renew', sa.Boolean(), nullable=True),
    sa.Column('renewal_notes', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('linkable_id', sa.Integer(), nullable=False),
    sa.Column('linkable_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_definition_id'], ['custom_field_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_field_value', schema=None) as batch_op:
        batch_op.create_index('idx_custom_value_linkable', ['linkable_type', 'linkable_id'], unique=False)

    op.create_table('framework_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('days_offset', sa.Integer(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('slack_target_channel', sa.String(length=50), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['email_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_code')
    )
    op.create_table('offboarding_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('new_hire_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_email', sa.String(length=120), nullable=True),
    sa.Column('personal_email', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_manager_id', sa.Integer(), nullable=True),
    sa.Column('assigned_buddy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_buddy_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['onboarding_pack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_chart_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('chart_data', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pack_communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['onboarding_pack.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=True),
    sa.Column('recipient_type', sa.String(length=50), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('slack_target_channel', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_communication', schema=None) as batch_op:
        batch_op.create_index('idx_scheduled_comm_status_date', ['status', 'scheduled_date'], unique=False)
        batch_op.create_index('idx_scheduled_comm_target', ['target_type', 'target_id'], unique=False)

    op.create_table('security_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('data_breach', sa.Boolean(), nullable=True),
    sa.Column('third_party_impacted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('iso_27001_control_references', sa.Text(), nullable=True, comment='Relevant ISO 27001 controls, e.g., A.12.1.2, A.14.2.1'),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('user_known_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_known_ips', schema=None) as batch_op:
        batch_op.create_index('idx_user_ip', ['user_id', 'ip_address'], unique=False)

    op.create_table('activity_execution_tags',
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['activity_execution.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('execution_id', 'tag_id')
    )
    op.create_table('bcdr_test_tags',
    sa.Column('test_log_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['test_log_id'], ['bcdr_test_log.id'], ),
    sa.PrimaryKeyConstraint('test_log_id', 'tag_id')
    )
    op.create_table('campaign_groups',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'group_id')
    )
    op.create_table('campaign_tags',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'tag_id')
    )
    op.create_table('campaign_users',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'user_id')
    )
    op.create_table('compliance_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('internal_lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.ForeignKeyConstraint(['internal_lead_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_control_id', sa.Integer(), nullable=False),
    sa.Column('linkable_id', sa.Integer(), nullable=False),
    sa.Column('linkable_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['framework_control_id'], ['framework_control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_link_linkable_id'), ['linkable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_link_linkable_type'), ['linkable_type'], unique=False)

    op.create_table('compliance_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_control_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_model', sa.String(length=50), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['framework_control_id'], ['framework_control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_mappings',
    sa.Column('source_control_id', sa.Integer(), nullable=False),
    sa.Column('target_control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_control_id'], ['framework_control.id'], ),
    sa.ForeignKeyConstraint(['target_control_id'], ['framework_control.id'], ),
    sa.PrimaryKeyConstraint('source_control_id', 'target_control_id')
    )
    op.create_table('course_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['course_assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_link', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_suppliers',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['security_incident.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'supplier_id')
    )
    op.create_table('incident_tags',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['security_incident.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'tag_id')
    )
    op.create_table('incident_users',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['security_incident.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'user_id')
    )
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('potential_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('estimated_close_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('primary_contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_acknowledgement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_version_groups',
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.PrimaryKeyConstraint('policy_version_id', 'group_id')
    )
    op.create_table('policy_version_users',
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('policy_version_id', 'user_id')
    )
    op.create_table('post_incident_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('lead_up', sa.Text(), nullable=True),
    sa.Column('fault', sa.Text(), nullable=True),
    sa.Column('impact_analysis', sa.Text(), nullable=True),
    sa.Column('detection', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('recovery', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['security_incident.id'], ),
    sa.ForeignKeyConstraint(['locked_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('process_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onboarding_process_id', sa.Integer(), nullable=True),
    sa.Column('offboarding_process_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('linked_object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offboarding_process_id'], ['offboarding_process.id'], ),
    sa.ForeignKeyConstraint(['onboarding_process_id'], ['onboarding_process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('validated_cost', sa.Float(), nullable=True),
    sa.Column('cost_validated_at', sa.DateTime(), nullable=True),
    sa.Column('cost_validated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['cost_validated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_id')
    )
    op.create_table('risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('extended_description', sa.Text(), nullable=True),
    sa.Column('threat_type_id', sa.Integer(), nullable=True),
    sa.Column('source_catalog_risk_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('treatment_strategy', sa.String(length=50), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('inherent_impact', sa.Integer(), nullable=True),
    sa.Column('inherent_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_impact', sa.Integer(), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_catalog_risk_id'], ['catalog_risk.id'], ),
    sa.ForeignKeyConstraint(['threat_type_id'], ['threat_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_activities',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['security_activity.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'activity_id')
    )
    op.create_table('service_certificates',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'certificate_id')
    )
    op.create_table('service_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_dependencies',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['business_service.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['business_service.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('service_policies',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'policy_id')
    )
    op.create_table('service_users',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'user_id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('renewal_period_type', sa.String(length=20), nullable=False),
    sa.Column('renewal_period_value', sa.Integer(), nullable=True),
    sa.Column('monthly_renewal_day', sa.String(length=10), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('internal_id', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('warranty_length', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('audit_control_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('original_control_id', sa.Integer(), nullable=True),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('control_title', sa.String(length=512), nullable=False),
    sa.Column('control_description', sa.Text(), nullable=True),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('internal_comments', sa.Text(), nullable=True),
    sa.Column('auditor_findings', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['compliance_audit.id'], ),
    sa.ForeignKeyConstraint(['original_control_id'], ['framework_control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_evidence',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=True),
    sa.Column('offboarding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['compliance_audit.id'], ),
    sa.ForeignKeyConstraint(['offboarding_id'], ['offboarding_process.id'], ),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding_process.id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('audit_participants',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['compliance_audit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('audit_id', 'user_id')
    )
    op.create_table('bcdr_plan_subscriptions',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['bcdr_plan.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'subscription_id')
    )
    op.create_table('cost_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('changed_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentation_tags',
    sa.Column('documentation_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documentation_id'], ['documentation.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('documentation_id', 'tag_id')
    )
    op.create_table('incident_subscriptions',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['security_incident.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'subscription_id')
    )
    op.create_table('incident_timeline_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['post_incident_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('license_key', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_tags',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('link_id', 'tag_id')
    )
    op.create_table('pack_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['onboarding_pack.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_cost_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_tags',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('purchase_id', 'tag_id')
    )
    op.create_table('purchase_users',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_id', 'user_id')
    )
    op.create_table('risk_affected_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('linkable_type', sa.String(length=50), nullable=False),
    sa.Column('linkable_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessment_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('original_risk_id', sa.Integer(), nullable=True),
    sa.Column('risk_description', sa.Text(), nullable=True),
    sa.Column('threat_type_name', sa.String(length=100), nullable=True),
    sa.Column('category_list', sa.String(length=255), nullable=True),
    sa.Column('inherent_impact', sa.Integer(), nullable=True),
    sa.Column('inherent_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_impact', sa.Integer(), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('treatment_strategy', sa.String(length=50), nullable=True),
    sa.Column('mitigation_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessment.id'], ),
    sa.ForeignKeyConstraint(['original_risk_id'], ['risk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_category_association',
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ),
    sa.PrimaryKeyConstraint('risk_id', 'category')
    )
    op.create_table('risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_mitigation_activities',
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['security_activity.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ),
    sa.PrimaryKeyConstraint('risk_id', 'activity_id')
    )
    op.create_table('risk_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('linkable_type', sa.String(length=50), nullable=False),
    sa.Column('linkable_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_documentation',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('documentation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documentation_id'], ['documentation.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'documentation_id')
    )
    op.create_table('subscription_contacts',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('subscription_id', 'contact_id')
    )
    op.create_table('subscription_payment_methods',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('subscription_id', 'payment_method_id')
    )
    op.create_table('subscription_tags',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('subscription_id', 'tag_id')
    )
    op.create_table('subscription_users',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('subscription_id', 'user_id')
    )
    op.create_table('asset_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_date', sa.DateTime(), nullable=True),
    sa.Column('checked_in_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['asset_inventory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_control_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_item_id', sa.Integer(), nullable=False),
    sa.Column('linkable_type', sa.String(length=50), nullable=False),
    sa.Column('linkable_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['audit_item_id'], ['audit_control_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bcdr_plan_assets',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['bcdr_plan.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'asset_id')
    )
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('break_glass', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index('idx_credential_owner', ['owner_type', 'owner_id'], unique=False)
        batch_op.create_index('idx_credential_software', ['software_id'], unique=False)

    op.create_table('incident_assets',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['security_incident.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'asset_id')
    )
    op.create_table('peripheral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_length', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('risk_assessment_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('linkable_type', sa.String(length=50), nullable=True),
    sa.Column('linkable_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['risk_assessment_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('commit_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credential_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('masked_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credential_secrets', schema=None) as batch_op:
        batch_op.create_index('idx_secret_credential', ['credential_id', 'is_active'], unique=False)
        batch_op.create_index('idx_secret_expiry', ['expires_at', 'is_active'], unique=False)

    op.create_table('disposal_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=False),
    sa.Column('disposal_method', sa.String(length=100), nullable=False),
    sa.Column('disposal_partner', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('peripheral_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripheral.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id'),
    sa.UniqueConstraint('peripheral_id')
    )
    op.create_table('maintenance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('ticket_link', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('peripheral_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripheral.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peripheral_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peripheral_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_date', sa.DateTime(), nullable=True),
    sa.Column('checked_in_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripheral.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_credentials',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'credential_id')
    )
    op.create_table('change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('risk_impact', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('test_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('configuration_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration.id'], ),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_version.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_service.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disposal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disposal_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['disposal_id'], ['disposal_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_log_tags',
    sa.Column('maintenance_log_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_log_id'], ['maintenance_log.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('maintenance_log_id', 'tag_id')
    )
    op.create_table('change_tags',
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('change_id', 'tag_id')
    )
    op.create_table('risk_assessment_changes',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessment.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.PrimaryKeyConstraint('assessment_id', 'change_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessment_changes')
    op.drop_table('change_tags')
    op.drop_table('maintenance_log_tags')
    op.drop_table('disposal_history')
    op.drop_table('change')
    op.drop_table('service_credentials')
    op.drop_table('peripheral_assignment')
    op.drop_table('maintenance_log')
    op.drop_table('disposal_record')
    with op.batch_alter_table('credential_secrets', schema=None) as batch_op:
        batch_op.drop_index('idx_secret_expiry')
        batch_op.drop_index('idx_secret_credential')

    op.drop_table('credential_secrets')
    op.drop_table('configuration_version')
    op.drop_table('risk_assessment_evidence')
    op.drop_table('peripheral')
    op.drop_table('incident_assets')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index('idx_credential_software')
        batch_op.drop_index('idx_credential_owner')

    op.drop_table('credentials')
    op.drop_table('configuration')
    op.drop_table('bcdr_plan_assets')
    op.drop_table('audit_control_link')
    op.drop_table('asset_inventory_item')
    op.drop_table('asset_history')
    op.drop_table('asset_assignment')
    op.drop_table('subscription_users')
    op.drop_table('subscription_tags')
    op.drop_table('subscription_payment_methods')
    op.drop_table('subscription_contacts')
    op.drop_table('service_documentation')
    op.drop_table('risk_reference')
    op.drop_table('risk_mitigation_activities')
    op.drop_table('risk_history')
    op.drop_table('risk_category_association')
    op.drop_table('risk_category')
    op.drop_table('risk_assessment_item')
    op.drop_table('risk_affected_item')
    op.drop_table('purchase_users')
    op.drop_table('purchase_tags')
    op.drop_table('purchase_cost_history')
    op.drop_table('pack_item')
    op.drop_table('link_tags')
    op.drop_table('license')
    op.drop_table('incident_timeline_event')
    op.drop_table('incident_subscriptions')
    op.drop_table('documentation_tags')
    op.drop_table('cost_history')
    op.drop_table('bcdr_plan_subscriptions')
    op.drop_table('audit_participants')
    op.drop_table('audit_evidence')
    op.drop_table('audit_control_item')
    op.drop_table('asset')
    op.drop_table('activity')
    op.drop_table('subscription')
    op.drop_table('service_users')
    op.drop_table('service_policies')
    op.drop_table('service_dependencies')
    op.drop_table('service_component')
    op.drop_table('service_certificates')
    op.drop_table('service_activities')
    op.drop_table('risk')
    op.drop_table('purchase')
    op.drop_table('process_item')
    op.drop_table('post_incident_review')
    op.drop_table('policy_version_users')
    op.drop_table('policy_version_groups')
    op.drop_table('policy_acknowledgement')
    op.drop_table('opportunity')
    op.drop_table('link')
    op.drop_table('incident_users')
    op.drop_table('incident_tags')
    op.drop_table('incident_suppliers')
    op.drop_table('documentation')
    op.drop_table('course_completion')
    op.drop_table('control_mappings')
    op.drop_table('contract_item')
    op.drop_table('compliance_rule')
    with op.batch_alter_table('compliance_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_link_linkable_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_link_linkable_id'))

    op.drop_table('compliance_link')
    op.drop_table('compliance_audit')
    op.drop_table('campaign_users')
    op.drop_table('campaign_tags')
    op.drop_table('campaign_groups')
    op.drop_table('bcdr_test_tags')
    op.drop_table('activity_execution_tags')
    with op.batch_alter_table('user_known_ips', schema=None) as batch_op:
        batch_op.drop_index('idx_user_ip')

    op.drop_table('user_known_ips')
    op.drop_table('user_groups')
    op.drop_table('software')
    op.drop_table('security_incident')
    op.drop_table('security_assessment')
    with op.batch_alter_table('scheduled_communication', schema=None) as batch_op:
        batch_op.drop_index('idx_scheduled_comm_target')
        batch_op.drop_index('idx_scheduled_comm_status_date')

    op.drop_table('scheduled_communication')
    op.drop_table('policy_version')
    op.drop_table('payment_method')
    op.drop_table('pack_communication')
    op.drop_table('org_chart_snapshot')
    op.drop_table('onboarding_process')
    op.drop_table('offboarding_process')
    op.drop_table('notification_event')
    op.drop_table('framework_control')
    with op.batch_alter_table('custom_field_value', schema=None) as batch_op:
        batch_op.drop_index('idx_custom_value_linkable')

    op.drop_table('custom_field_value')
    op.drop_table('course_assignment')
    op.drop_table('contract')
    op.drop_table('contact')
    op.drop_table('certificate_versions')
    op.drop_table('catalog_risk')
    op.drop_table('candidate')
    op.drop_table('campaign')
    op.drop_table('business_service')
    op.drop_table('bcdr_test_log')
    op.drop_table('asset_inventory')
    op.drop_table('activity_tags')
    with op.batch_alter_table('activity_related_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_related_object_related_object_type'))
        batch_op.drop_index(batch_op.f('ix_activity_related_object_related_object_id'))

    op.drop_table('activity_related_object')
    op.drop_table('activity_participants')
    op.drop_table('activity_execution')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_token'))

    op.drop_table('user')
    op.drop_table('threat_type')
    op.drop_table('tag')
    op.drop_table('supplier')
    op.drop_table('security_activity')
    op.drop_table('risk_catalog')
    op.drop_table('risk_assessment')
    op.drop_table('process_template')
    op.drop_table('policy')
    op.drop_table('organization_settings')
    op.drop_table('onboarding_pack')
    op.drop_table('notification_setting')
    op.drop_table('location')
    op.drop_table('lead')
    op.drop_table('hiring_stage')
    op.drop_table('group')
    with op.batch_alter_table('framework', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_is_active'))

    op.drop_table('framework')
    op.drop_table('finance_settings')
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rate_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_exchange_rate_currency_code'))
        batch_op.drop_index('idx_exchange_rate_currency_date')

    op.drop_table('exchange_rate')
    op.drop_table('email_template')
    op.drop_table('custom_field_definition')
    op.drop_table('course')
    with op.batch_alter_table('cost_center', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_center_code'))

    op.drop_table('cost_center')
    op.drop_table('certificates')
    op.drop_table('budget')
    op.drop_table('bcdr_plan')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index('idx_attachment_linkable')

    op.drop_table('attachment')
    # ### end Alembic commands ###
