"""Add Module model

Revision ID: 927d50e1ec0c
Revises: 7cd37de826eb
Create Date: 2026-01-24 10:32:47.152625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927d50e1ec0c'
down_revision = '7cd37de826eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_slug'))

    op.drop_table('module')
    # ### end Alembic commands ###
