"""Initial migration

Revision ID: cadd000a5014
Revises: b06a4a8e3bf5
Create Date: 2026-01-24 14:03:57.240497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadd000a5014'
down_revision = 'b06a4a8e3bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first (PostgreSQL requires this)
    accesslevel_enum = sa.Enum('READ_ONLY', 'WRITE', name='accesslevel', create_type=False)
    accesslevel_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', sa.Enum('READ_ONLY', 'WRITE', name='accesslevel'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('access_level')

    # ### end Alembic commands ###
